moviedb/config/routes.rb
Moviedb::Application.routes.draw do

  resources :movies
  resources :genres

end

moviedb/app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name

  has_many :movies

  # validates_presence_of :name
  # validates_uniqueness_of :name
  # validates_length_of :name, :minimum => 3
  #
  # also possible, but does not make sense here:
  # validates_inclusion_of :name, :in => ['Action', 'Science Fiction']

  validates :name,
    :presence => true,
    :uniqueness => true,
    :length => { :minimum => 3 }

end

moviedb/app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :language, :length, :title, :year, :genre_id

  belongs_to :genre

  validates_presence_of :title, :year
  validates_uniqueness_of :title

  def to_param
    "#{id}-#{title.parameterize}"
  end

end

moviedb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

moviedb/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  respond_to :html, :json

  def index
    respond_with @genres = Genre.order('name').all
  end

  def show
    respond_with @genre = Genre.find(params[:id])
  end

  def edit
    respond_with @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update_attributes(params[:genre])
    respond_with @genre
  end

  def new
    respond_with @genre = Genre.new
  end

  def create
    @genre = Genre.new(params[:genre])
    @genre.save
    respond_with @genre
  end

  def destroy
    Genre.find(params[:id]).destroy
    redirect_to genres_path
  end

end

moviedb/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_filter :load_movie, :only => [:show, :edit, :update, :destroy]
  respond_to :html, :json, :xml

  def index
    @movies = Movie.all
    respond_with(@movies, :except => :id)
  end

  def show
    respond_with(@movie, :except => :id)
  end

  def edit
    respond_with(@movie, :except => :id)
  end

  def update
    @movie.update_attributes(params[:movie])
    respond_with @movie
    ## -> same as one line above
    # if @movie.update_attributes(params[:movie])
    #   redirect_to movie_path(@movie)
    # else
    #   render :action => 'edit'
    # end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(params[:movie])
    @movie.save
    respond_with @movie
    ## -> same as one line above
    # if @movie.save
    #   redirect_to movie_path(@movie)
    # else
    #   render :action => 'new'
    # end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

private

  def load_movie
    @movie = Movie.find(params[:id])
  end

end

moviedb/app/helpers/application_helper.rb
module ApplicationHelper
end

moviedb/app/helpers/genres_helper.rb
module GenresHelper
end

moviedb/app/helpers/movies_helper.rb
module MoviesHelper

  def delete_movie_link (movie)
    link_to "Delete", movie_path(movie),
     :method => :delete,
     :confirm => "Are you sure?"
  end

end

moviedb/app/views/genres/_genre.html.slim
li= link_to genre.name, genre_path(genre)

moviedb/app/views/genres/index.html.slim
h1 List of Genres

ul= render @genres

moviedb/app/views/genres/show.html.slim
h1= @genre.name

ul= render @genre.movies

moviedb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviedb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

moviedb/app/views/movies/_form.html.slim
= form_for @movie do |form|

  p
    = form.label :title
    = form.text_field :title
    = @movie.errors[:title].to_sentence

  p
    = form.label :genre
    = form.collection_select :genre_id,
      Genre.all,
      :id,
      :name,
      :include_blank => true

  p
    = form.label :year
    = form.text_field :year
    = @movie.errors[:title].to_sentence

  p
    = form.label :length
    = form.text_field :length

  p
    = form.label :language
    = form.text_field :language

  = form.submit

= link_to "Back", movies_path

moviedb/app/views/movies/_movie.html.slim
li= link_to movie.title, movie

moviedb/app/views/movies/edit.html.slim
h1 Editing "#{ @movie.title_was }"

= render 'form'

moviedb/app/views/movies/index.html.slim
h1 All the movies
p= link_to "New movie", new_movie_path

ul= render @movies

/ %ul
/   - @movies.each do |movie|
/     %li= link_to movie.title, movie

moviedb/app/views/movies/new.html.slim
h1 New Movie
= render 'form'

moviedb/app/views/movies/show.html.slim
h1
  = @movie.title
  - if @movie.year.present?
    | (#{@movie.year})

/ view genre if available
p
  - if @movie.genre.present?
    | Genre: #{ link_to @movie.genre.name, @movie.genre }
  br
  | Length: #{@movie.length} minutes
  br
  | Language: #{@movie.language}
p
  =' link_to "Edit", edit_movie_path(@movie)
  =' delete_movie_link(@movie)
  = link_to "Back to all movies", movies_path